import { type NextRequest } from 'next/server'
import { updateSession } from '@/lib/supabase/middleware'

// `middleware` was renamed to `proxy` in Next.js 16. This file must live at the
// same level as `app` — i.e. inside `src/` — to be picked up.
export async function proxy(request: NextRequest) {
  return updateSession(request)
}

export const config = {
  matcher: [
    /*
     * Match all request paths except static assets, image optimization, and
     * the extension-less icon/manifest routes generated by Next's app dir
     * (icon, apple-icon, icon-192, icon-512, manifest.webmanifest).
     */
    '/((?!_next/static|_next/image|favicon.ico|icon$|apple-icon$|icon-192$|icon-512$|manifest.webmanifest$|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
}
